# Data Science: Films

## Onderzoeksvragen

1. In hoeverre is de omzet van een film te voorspellen op basis van de populariteit op Facebook en IMDB zelf?
2. In hoeverre zijn er groepen te onderscheiden op basis van budget, score en facebook likes?
3. In hoeverre is een relatie te zien tussen de omzet van de film en de verhouding tussen de geslacht van een directeur van een film?

## Proces stap 1 t/m 4

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
pd.set_option('display.max_columns', 100)

## Stap 1: Data collection

In [2]:
df_movies = pd.read_csv('movie.csv')

In [3]:
df_movies.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,106759,Joseph Gordon-Levitt,0.0,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force AwakensÂ ...,8,143,NaN,0.0,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [4]:
df_movies.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [5]:
df_movies.dtypes

color                         object
director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
movie_title                   object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews         float64
language                      object
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
movie_facebook_likes           int64
dtype: object

## Stap 2: Data Processing

In [11]:
cols = ['movie_title', 'imdb_score', 'title_year',
        'genres', 'duration', 'budget', 'gross',
        'color', 'language', 'country',  'director_name', 'actor_1_name', 
        'actor_2_name', 'actor_3_name',  
        'movie_imdb_link', 'facenumber_in_poster', 'plot_keywords', 
        'content_rating', 'aspect_ratio', 'num_user_for_reviews', 
        'num_voted_users', 'num_critic_for_reviews', 
        'movie_facebook_likes', 'director_facebook_likes', 
        'actor_1_facebook_likes', 'actor_2_facebook_likes', 
        'actor_3_facebook_likes', 'cast_total_facebook_likes']
df_movies = df_movies[cols]

In [12]:
df_movies.head()

,movie_title,imdb_score,title_year,genres,duration,budget,gross,color,language,country,director_name,actor_1_name,actor_2_name,actor_3_name,movie_imdb_link,facenumber_in_poster,plot_keywords,content_rating,aspect_ratio,num_user_for_reviews,num_voted_users,num_critic_for_reviews,movie_facebook_likes,director_facebook_likes,actor_1_facebook_likes,actor_2_facebook_likes,actor_3_facebook_likes,cast_total_facebook_likes
0,Avatar,7.9,2009.0,Action|Adventure|Fantasy|Sci-Fi,178.0,237000000.0,760505847.0,Color,English,USA,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,0.0,avatar|future|marine|native|paraplegic,PG-13,1.78,3054.0,886204,723.0,33000,0.0,1000.0,936.0,855.0,4834
1,Pirates of the Caribbean: At World's End,7.1,2007.0,Action|Adventure|Fantasy,169.0,300000000.0,309404152.0,Color,English,USA,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,0.0,goddess|marriage ceremony|marriage proposal|pi...,PG-13,2.35,1238.0,471220,302.0,0,563.0,40000.0,5000.0,1000.0,48350
2,Spectre,6.8,2015.0,Action|Adventure|Thriller,148.0,245000000.0,200074175.0,Color,English,UK,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,1.0,bomb|espionage|sequel|spy|terrorist,PG-13,2.35,994.0,275868,602.0,85000,0.0,11000.0,393.0,161.0,11700
3,The Dark Knight Rises,8.5,2012.0,Action|Thriller,164.0,250000000.0,448130642.0,Color,English,USA,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,0.0,deception|imprisonment|lawlessness|police offi...,PG-13,2.35,2701.0,1144337,813.0,164000,22000.0,27000.0,23000.0,23000.0,106759
4,Star Wars: Episode VII - The Force AwakensÂ ...,7.1,NaN,Documentary,NaN,NaN,NaN,NaN,NaN,NaN,Doug Walker,Doug Walker,Rob Walker,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,0.0,NaN,NaN,NaN,NaN,8,NaN,0,131.0,131.0,12.0,NaN,143

## Stap 3: Data cleaning

In [13]:
pd.notnull(df_movies).sum()

movie_title                  5043
imdb_score                   5043
title_year                   4935
genres                       5043
duration                     5028
budget                       4551
gross                        4159
color                        5024
language                     5031
country                      5038
director_name                4939
actor_1_name                 5036
actor_2_name                 5030
actor_3_name                 5020
movie_imdb_link              5043
facenumber_in_poster         5030
plot_keywords                4890
content_rating               4740
aspect_ratio                 4714
num_user_for_reviews         5022
num_voted_users              5043
num_critic_for_reviews       4993
movie_facebook_likes         5043
director_facebook_likes      4939
actor_1_facebook_likes       5036
actor_2_facebook_likes       5030
actor_3_facebook_likes       5020
cast_total_facebook_likes    5043
dtype: int64

In [14]:
pd.isnull(df_movies).sum()

movie_title                    0
imdb_score                     0
title_year                   108
genres                         0
duration                      15
budget                       492
gross                        884
color                         19
language                      12
country                        5
director_name                104
actor_1_name                   7
actor_2_name                  13
actor_3_name                  23
movie_imdb_link                0
facenumber_in_poster          13
plot_keywords                153
content_rating               303
aspect_ratio                 329
num_user_for_reviews          21
num_voted_users                0
num_critic_for_reviews        50
movie_facebook_likes           0
director_facebook_likes      104
actor_1_facebook_likes         7
actor_2_facebook_likes        13
actor_3_facebook_likes        23
cast_total_facebook_likes      0
dtype: int64

In [15]:
df_movies.dropna(inplace=True)

In [16]:
pd.isnull(df_movies).sum()

movie_title                  0
imdb_score                   0
title_year                   0
genres                       0
duration                     0
budget                       0
gross                        0
color                        0
language                     0
country                      0
director_name                0
actor_1_name                 0
actor_2_name                 0
actor_3_name                 0
movie_imdb_link              0
facenumber_in_poster         0
plot_keywords                0
content_rating               0
aspect_ratio                 0
num_user_for_reviews         0
num_voted_users              0
num_critic_for_reviews       0
movie_facebook_likes         0
director_facebook_likes      0
actor_1_facebook_likes       0
actor_2_facebook_likes       0
actor_3_facebook_likes       0
cast_total_facebook_likes    0
dtype: int64

In [17]:
pd.notnull(df_movies).sum()

movie_title                  3756
imdb_score                   3756
title_year                   3756
genres                       3756
duration                     3756
budget                       3756
gross                        3756
color                        3756
language                     3756
country                      3756
director_name                3756
actor_1_name                 3756
actor_2_name                 3756
actor_3_name                 3756
movie_imdb_link              3756
facenumber_in_poster         3756
plot_keywords                3756
content_rating               3756
aspect_ratio                 3756
num_user_for_reviews         3756
num_voted_users              3756
num_critic_for_reviews       3756
movie_facebook_likes         3756
director_facebook_likes      3756
actor_1_facebook_likes       3756
actor_2_facebook_likes       3756
actor_3_facebook_likes       3756
cast_total_facebook_likes    3756
dtype: int64

In [18]:
df_movies.head()

,movie_title,imdb_score,title_year,genres,duration,budget,gross,color,language,country,director_name,actor_1_name,actor_2_name,actor_3_name,movie_imdb_link,facenumber_in_poster,plot_keywords,content_rating,aspect_ratio,num_user_for_reviews,num_voted_users,num_critic_for_reviews,movie_facebook_likes,director_facebook_likes,actor_1_facebook_likes,actor_2_facebook_likes,actor_3_facebook_likes,cast_total_facebook_likes
0,Avatar,7.9,2009.0,Action|Adventure|Fantasy|Sci-Fi,178.0,237000000.0,760505847.0,Color,English,USA,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,0.0,avatar|future|marine|native|paraplegic,PG-13,1.78,3054.0,886204,723.0,33000,0.0,1000.0,936.0,855.0,4834
1,Pirates of the Caribbean: At World's End,7.1,2007.0,Action|Adventure|Fantasy,169.0,300000000.0,309404152.0,Color,English,USA,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,0.0,goddess|marriage ceremony|marriage proposal|pi...,PG-13,2.35,1238.0,471220,302.0,0,563.0,40000.0,5000.0,1000.0,48350
2,Spectre,6.8,2015.0,Action|Adventure|Thriller,148.0,245000000.0,200074175.0,Color,English,UK,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,1.0,bomb|espionage|sequel|spy|terrorist,PG-13,2.35,994.0,275868,602.0,85000,0.0,11000.0,393.0,161.0,11700
3,The Dark Knight Rises,8.5,2012.0,Action|Thriller,164.0,250000000.0,448130642.0,Color,English,USA,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,0.0,deception|imprisonment|lawlessness|police offi...,PG-13,2.35,2701.0,1144337,813.0,164000,22000.0,27000.0,23000.0,23000.0,106759
5,John Carter,6.6,2012.0,Action|Adventure|Sci-Fi,132.0,263700000.0,73058679.0,Color,English,USA,Andrew Stanton,Daryl Sabara,Samantha Morton,Polly Walker,http://www.imdb.com/title/tt0401729/?ref_=fn_t...,1.0,alien|american civil war|male nipple|mars|prin...,PG-13,2.35,738.0,212204,462.0,24000,475.0,640.0,632.0,530.0,1873

## Stap 4: Data exploration

In [19]:
df_movies.describe()

,imdb_score,title_year,duration,budget,gross,facenumber_in_poster,aspect_ratio,num_user_for_reviews,num_voted_users,num_critic_for_reviews,movie_facebook_likes,director_facebook_likes,actor_1_facebook_likes,actor_2_facebook_likes,actor_3_facebook_likes,cast_total_facebook_likes
count,3756.000000,3756.000000,3756.000000,3.756000e+03,3.756000e+03,3756.000000,3756.000000,3756.000000,3.756000e+03,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000
mean,6.465282,2002.976571,110.257987,4.623685e+07,5.261282e+07,1.377263,2.111014,336.843184,1.058267e+05,167.378328,9353.829340,807.336528,7751.338658,2021.775825,771.279553,11527.101970
std,1.056247,9.888108,22.646717,2.260103e+08,7.031787e+07,2.041541,0.353068,411.227368,1.520354e+05,123.452040,21462.889123,3068.171683,15519.339621,4544.908236,1894.249869,19122.176905
min,1.600000,1927.000000,37.000000,2.180000e+02,1.620000e+02,0.000000,1.180000,4.000000,9.100000e+01,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5.900000,1999.000000,96.000000,1.000000e+07,8.270233e+06,0.000000,1.850000,110.000000,1.966700e+04,77.000000,0.000000,11.000000,745.000000,384.750000,194.000000,1919.750000
50%,6.600000,2004.000000,106.000000,2.500000e+07,3.009311e+07,1.000000,2.350000,210.000000,5.397350e+04,138.500000,227.000000,64.000000,1000.000000,685.500000,436.000000,4059.500000
75%,7.200000,2010.000000,120.000000,5.000000e+07,6.688194e+07,2.000000,2.350000,398.250000,1.286020e+05,224.000000,11000.000000,235.000000,13000.000000,976.000000,691.000000,16240.000000
max,9.300000,2016.000000,330.000000,1.221550e+10,7.605058e+08,43.000000,16.000000,5060.000000,1.689764e+06,813.000000,349000.000000,23000.000000,640000.000000,137000.000000,23000.000000,656730.000000

# Onderzoeksvraag 3: 

### In hoeverre is een relatie te zien tussen de omzet van de film en de verhouding tussen de geslacht van een directeur van een film?